### ISSUE TITLE
different  ssim_loss curves

### ISSUE THREAD

**Issue by IPNUISTlegal** [hli1221/imagefusion_densefuse#1]
![image](https://user-images.githubusercontent.com/35527568/50964598-a5fa2080-150a-11e9-8312-0d47e1c48f26.png)
李博您好，我是python初学者，我很好奇一个图里面是如何同时拥有四条不同的loss曲线的，代码具体如何实现？因为很少能在cv论文中看到有这么多不同loss的曲线图

**Comment by hli1221** [comment]
感谢你的关注，我是先在python里得到数据，然后用matlab画的曲线
