### ISSUE TITLE
How to feed train data

### ISSUE THREAD

**Issue by strawberry1996** [hli1221/imagefusion_densefuse#2]
Hello, I want to use your code to fusion 10 images into one, but I don't know how to input 10 images , I read your code and I find that in your code , you just input one image . and where is the generate.py used ?

**Comment by hli1221** [comment]
You can find 'generate' in 'main.py'. For testing phase, 'IS_TRAINING = False'. 
And in this 'generate' function, two images are fused.

**Comment by strawberry1996** [comment]
Thanks for your answer, I guess that the process of image fusion and training is separate, this right? in other words, when we training , we don't fuse these image, after train, we get the model, then we can use the model to fusion our image.

**Comment by hli1221** [comment]
Yes, you are right.

**Comment by 6xfh** [comment]
你好！我是新手，想深入学习您的代码，请问有训练的步骤么？谢谢

**Comment by hli1221** [comment]
你好。训练和测试的相关代码入口都在main.py中可以找到。train_recons.py中是训练的主要代码
