### ISSUE TITLE
感谢信

### ISSUE THREAD

**Issue by Keep-Passion** [hli1221/imagefusion_densefuse#8]
李博您好，非常感谢您的工作，它给我很大启发，我在您的基础上改进并运用到多聚焦图像融合问题上，这是我新写的文章，[链接](https://arxiv.org/abs/1908.01703)，这里面也引用了您的文章。我发现在表达Auto-encoder结构中您的原图画的非常好，我没找到比这个更好的表示方式，于是我在您基础上按照我的创新点改成我的示意图，想获得您的许可。另外，如果可以的话，我非常希望您能对我的工作能指点一二，这是我的荣幸。

**Comment by hli1221** [comment]
感谢你引用我们的工作，关于auto-encoder框架图你完全可以在此基础上做修改。
你的论文我看了，写的很好，我也向你学习。
祝你的论文早日能够被录用。
